name: word_flash
description: A simple word memorization app for CET-4.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  path: ^1.9.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  provider: ^6.0.5
  firebase_core: ^2.16.0   # 添加firebase_core依赖
  firebase_auth: ^4.6.8  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/words/english-vocabulary-master/json/converted-5-考研-顺序.json
    - assets/images/logo.png